project_id = "xuyokixtlmchqwibntep"

[functions.ai-guardian-chat]
verify_jwt = true

[functions.ineke-chat]
verify_jwt = true

[functions.clara-chat]
verify_jwt = false

[functions.clara-checkout]
verify_jwt = false
